### ISSUE TITLE
Windows 10 Launch Issue

### ISSUE THREAD

**Issue by elliottsm** [Razzmatazzz/ValheimSaveShield#2]
Having launching issue with Windows 10 (20H2).  Nothing appears after attempting to launch. I have verified that the correct .net version is installed. 
Here is some details from Event Viewer, maybe this will help

Faulting application name: ValheimSaveShield.exe, version: 0.1.1.0, time stamp: 0xb0a27d80
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0xb610d74d
Exception code: 0xe0434352
Fault offset: 0x0012a8b2
Faulting process id: 0x1c78
Faulting application start time: 0x01d702dafbc805d4
Faulting application path: C:\Users\User\Desktop\ValheimSaveShield.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 549b959f-abbc-4e6c-ae2f-31d84890a729
Faulting package full name: 
Faulting package-relative application ID: 

Application: ValheimSaveShield.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.FileSystemWatcher.set_Path(System.String)
   at ValheimSaveShield.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)

**Comment by Razzmatazzz** [comment]
Thanks for the report. This might seem like a strange question, but you you have the game client installed, the dedicated server, or both installed?

**Comment by jeriks31** [comment]
Having the same exact same issue as described. In my case it's on a separate computer that only has dedicated server files

**Comment by Razzmatazzz** [comment]
I just released a new version that should fix these crashes. A couple notes:
Due to a desire to keep things simple, whichever folder you select for your Valheim saves MUST have both "worlds" and "characters" subfolders. Your world saves are obviously stored in the "worlds" subfolder.

**Comment by elliottsm** [comment]
Only the dedicated server
________________________________

**Comment by jeriks31** [comment]
New version fixed it for me, thanks!

**Comment by tankcom** [comment]
Had the same issue on v.0.1.2.0 on my dedicated server(no character save and no game installed). After I transfered the character save folder to my dedicated server it worked.

**Comment by Razzmatazzz** [comment]
You just need the "characters" folder to exist, but it can be empty. I'll probably make the program create that folder if it doesn't exist.

**Comment by elliottsm** [comment]
Still same issue, it ran once then it wont launch again, I added the characters folder as well still same issue.

Must be my PC then, as its working for others (shrug)

**Comment by Razzmatazzz** [comment]
I just released a new version that might fix the problem for you. If it still doesn't work, try clearing the app settings:

1. Push windows key+R
2. paste in: %userprofile%/appdata/local/ValheimSaveShield/
3. Push OK
4. Delete all the folders in there
5. Try to launch the app again

**Comment by Razzmatazzz** [comment]
Did any of you select a "backups" folder that contained files from other backups you were making? If so, try pointing it to a fresh backups folder.

**Comment by Razzmatazzz** [comment]
@elliottsm Does the app still not launch for you?

**Comment by elliottsm** [comment]
Sorry, off on holiday this week will check Friday when I get back
________________________________

**Comment by cgidfar** [comment]
@Razzmatazzz I was having a similar issue earlier. Here are the steps to reproduce it:

The problem seems to happen when, from an earlier version (3.0.0), I change the backup folder to a different location, and choose to move the existing backups to that new location. That leaves a folder at LocalLow/IronGate/Valheim/backups which is empty (so it does not contain the 'character' and 'world' subfolders). 

Then, I try to run a new version (3.2.0), which I believe generates a new user.config file that by default points the empty LocalLow/IronGate/Valheim/backups. This causes the application to fail to start. If I manually delete LocalLow/IronGate/Valheim/backups, the application can then start as usual.

Hope this helps! Thanks for developing this, it's very nice for peace of mind.

**Comment by cgidfar** [comment]
@Razzmatazzz I was having a similar issue even on the newer version (3.2.0). I think the problem is that the default LocalLow/IronGate/Valheim/backups folder that VSS creates also must have the character and world folders, and those can be removed if on an earlier version the backup location is changed and the files moved to that new backup location.

I resolved my issue by deleting LocalLow/IronGate/Valheim/backups and having the application generate a new one. Hope that helps!

**Comment by Razzmatazzz** [comment]
@cgidfar Thank you! that was absolutely an issue. The next release will fix it by creating those folders when they don't exist.

**Comment by elliottsm** [comment]
Everything is working perfectly now!

Thank you
